### ISSUE TITLE
Question: why is the source code for thist module not available

### ISSUE THREAD

**Issue by ckolumbus** [JustinGrote/SecretManagement.JustinGrote.Credman#1]
Hi, i'm looking into adopting the PS SecretManagement module and was interested in the CredentialManager Vault that I found on PSGallery. 

Is there a reason why the source code is not available?

Thanks for you time & effort and all the projects you provide!
Chris

**Comment by JustinGrote** [comment]
Source isn't available because it's just a slight rework of https://github.com/PowerShell/SecretManagement/tree/main/ExtensionModules/CredManStore

I plan to deprecate this module and point to the much better [DPAPING ](https://github.com/jborean93/SecretManagement.DpapiNG) module by @jborean93
